services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/data
    command: redis-server --appendonly yes
  db: 
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  web:
    build: .